#!/bin/sh

if [ "$#" -eq 0 ]; then
  echo "Usage: #!/bin/dockerfile-shebang"
  exit 1
fi

set -e

NAME=$(basename "$1")
docker build -t "$NAME" - < "$1" > /dev/null
shift # Remove script name from arguments
docker run --rm --name "$NAME" "$NAME" $@
